// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: waveshare

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
    /* SquareLine exports assume 0, but some panels need the framebuffer bytes
       swapped to get red and blue the right way round. Warn instead of failing
       the build so that remains a one-line fix in lv_conf.h. */
    #warning "LV_COLOR_16_SWAP is 1; SquareLine Studio assets were exported for 0"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    /* setup() and the /flash-mode endpoint both call this to repaint a status
       message. Building the screen a second time would orphan every widget
       created by the first pass, so bail out if we are already up. */
    static bool ui_built = false;
    if (ui_built) {
        if (ui_Screen1) lv_disp_load_scr(ui_Screen1);
        return;
    }
    ui_built = true;

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}

void ui_destroy(void)
{
    ui_Screen1_screen_destroy();
}
